FROM --platform=linux/amd64 python:3.10-slim-bookworm

RUN apt-get update && apt-get install -y \
    openjdk-17-jdk \
    curl \
    git \
    build-essential \
    bash-completion \
    && rm -rf /var/lib/apt/lists/* && \
    echo 'if [ -f /usr/share/bash-completion/bash_completion ]; then' \
     >> /etc/bash.bashrc && \
    echo '  . /usr/share/bash-completion/bash_completion' \
     >> /etc/bash.bashrc && \
    echo 'fi' \
     >> /etc/bash.bashrc

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# ENV PATH="$HOME/.local/bin:$PATH"
ENV PATH="/root/.local/bin:${PATH}"

COPY pyproject.toml ./

# RUN uv python install $UV_PYTHON_VERSION && \
#     uv python pin --global $UV_PYTHON_VERSION && \
RUN uv sync

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /workspace

CMD ["sleep", "infinity"]
